### ISSUE TITLE
make error 

### ISSUE THREAD

**Issue by albertyou2** [Gaffey/PedestrianTracking#1]
hi @Gaffey 

when i run make command ,i got this error:

In file included from /home/sojoyoo/pedestrian_gaffey/src/kcf.h:6:0,
                 from /home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:1:
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:50: error: ‘function’ in namespace ‘std’ does not name a template type
     ComplexMat_<T> mat_const_operator(const std::function<void(std::complex<T> 
                                                  ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:58: error: expected ‘,’ or ‘...’ before ‘<’ token
     ComplexMat_<T> mat_const_operator(const std::function<void(std::complex<T> 
                                                          ^
In file included from /home/sojoyoo/pedestrian_gaffey/src/kcf.h:7:0,
                 from /home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:1:
/home/sojoyoo/pedestrian_gaffey/src/extractfeatures.h:12:56: warning: unused parameter ‘useCNNFeature’ [-Wunused-parameter]
  Features(bool useHOGFeature, bool useYUVFeature, bool useCNNFeature):useHOGFea
                                                        ^
In file included from /home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:1:0:
/home/sojoyoo/pedestrian_gaffey/src/kcf.h: In constructor ‘KCF::KCF(double, double, double, int*)’:
/home/sojoyoo/pedestrian_gaffey/src/kcf.h:36:29: warning: ‘KCF::outputSigmaFactor’ will be initialized after [-Wreorder]
  double outputSigmaFactor = 0.1;
                             ^
/home/sojoyoo/pedestrian_gaffey/src/kcf.h:33:18: warning:   ‘double KCF::lambda’ [-Wreorder]
  double lambda = 1e-4;
                  ^
/home/sojoyoo/pedestrian_gaffey/src/kcf.h:18:2: warning:   when initialized here [-Wreorder]
  KCF(double gaussSigma, double outputSigmaFactor, double lambda, int *win):
  ^
In file included from /home/sojoyoo/pedestrian_gaffey/src/kcf.h:6:0,
                 from /home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:1:
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp: In instantiation of ‘ComplexMat_<T> ComplexMat_<T>::operator+(const T&) const [with T = float]’:
/home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:53:35:   required from here
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:93:34: error: no matching function for call to ‘ComplexMat_<float>::mat_const_operator(ComplexMat_<T>::operator+(const T&) const [with T = float]::<lambda(std::complex<float>&)>) const’
         return mat_const_operator( [&rhs](std::complex<T> & c) { c += rhs; });
                                  ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:20: note: candidate: ComplexMat_<T> ComplexMat_<T>::mat_const_operator(int) const [with T = float]
     ComplexMat_<T> mat_const_operator(const std::function<void(std::complex<T> 
                    ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:20: note:   no known conversion for argument 1 from ‘ComplexMat_<T>::operator+(const T&) const [with T = float]::<lambda(std::complex<float>&)>’ to ‘int’
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp: In instantiation of ‘ComplexMat_<T> ComplexMat_<T>::operator*(const T&) const [with T = float]’:
/home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:106:36:   required from here
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:89:34: error: no matching function for call to ‘ComplexMat_<float>::mat_const_operator(ComplexMat_<T>::operator*(const T&) const [with T = float]::<lambda(std::complex<float>&)>) const’
         return mat_const_operator( [&rhs](std::complex<T> & c) { c *= rhs; });
                                  ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:20: note: candidate: ComplexMat_<T> ComplexMat_<T>::mat_const_operator(int) const [with T = float]
     ComplexMat_<T> mat_const_operator(const std::function<void(std::complex<T> 
                    ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:20: note:   no known conversion for argument 1 from ‘ComplexMat_<T>::operator*(const T&) const [with T = float]::<lambda(std::complex<float>&)>’ to ‘int’
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp: In instantiation of ‘ComplexMat_<T> ComplexMat_<T>::sqr_mag() const [with T = float]’:
/home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:302:51:   required from here
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:46:34: error: invalid user-defined conversion from ‘ComplexMat_<T>::sqr_mag() const [with T = float]::<lambda(std::complex<float>&)>’ to ‘int’ [-fpermissive]
         return mat_const_operator( [](std::complex<T> & c) { c = c.real()*c.rea
                                  ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:46:58: note: candidate is: ComplexMat_<T>::sqr_mag() const [with T = float]::<lambda(std::complex<float>&)>::operator void (*)(std::complex<float>&)() const <near match>
         return mat_const_operator( [](std::complex<T> & c) { c = c.real()*c.rea
                                                          ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:46:58: note:   no known conversion from ‘void (*)(std::complex<float>&)’ to ‘int’
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:20: note:   initializing argument 1 of ‘ComplexMat_<T> ComplexMat_<T>::mat_const_operator(int) const [with T = float]’
     ComplexMat_<T> mat_const_operator(const std::function<void(std::complex<T> 
                    ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp: In instantiation of ‘ComplexMat_<T> ComplexMat_<T>::conj() const [with T = float]’:
/home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:302:68:   required from here
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:51:34: error: invalid user-defined conversion from ‘ComplexMat_<T>::conj() const [with T = float]::<lambda(std::complex<float>&)>’ to ‘int’ [-fpermissive]
         return mat_const_operator( [](std::complex<T> & c) { c = std::complex<T
                                  ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:51:58: note: candidate is: ComplexMat_<T>::conj() const [with T = float]::<lambda(std::complex<float>&)>::operator void (*)(std::complex<float>&)() const <near match>
         return mat_const_operator( [](std::complex<T> & c) { c = std::complex<T
                                                          ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:51:58: note:   no known conversion from ‘void (*)(std::complex<float>&)’ to ‘int’
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:20: note:   initializing argument 1 of ‘ComplexMat_<T> ComplexMat_<T>::mat_const_operator(int) const [with T = float]’
     ComplexMat_<T> mat_const_operator(const std::function<void(std::complex<T> 
                    ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp: In instantiation of ‘ComplexMat_<T> ComplexMat_<T>::mat_const_operator(int) const [with T = float]’:
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:93:34:   required from ‘ComplexMat_<T> ComplexMat_<T>::operator+(const T&) const [with T = float]’
/home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:53:35:   required from here
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:148:19: error: ‘op’ was not declared in this scope
                 op(*lhs);
                   ^
src/CMakeFiles/kcf.dir/build.make:62: recipe for target 'src/CMakeFiles/kcf.dir/kcf.cpp.o' failed
make[2]: *** [src/CMakeFiles/kcf.dir/kcf.cpp.o] Error 1
CMakeFiles/Makefile2:125: recipe for target 'src/CMakeFiles/kcf.dir/all' failed
make[1]: *** [src/CMakeFiles/kcf.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
sojoyoo@sojoyoo-System-Product-Name:~/pedestrian_gaffey/build$ cmake ..
-- OpenCV_LIB_DIR: /opt/ros/kinetic/share/OpenCV-3.1.0-dev/3rdparty/lib
-- OpenCV_INCLUDE_DIRS: /opt/ros/kinetic/include/opencv-3.1.0-dev/opencv;/opt/ros/kinetic/include/opencv-3.1.0-dev
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sojoyoo/pedestrian_gaffey/build
sojoyoo@sojoyoo-System-Product-Name:~/pedestrian_gaffey/build$ make
[ 14%] Building CXX object src/Hogtools/CMakeFiles/features.dir/gradientMex.cpp.o
/home/sojoyoo/pedestrian_gaffey/src/Hogtools/gradientMex.cpp: In function ‘void hog(float*, float*, float*, int, int, int, int, int, bool, float)’:
/home/sojoyoo/pedestrian_gaffey/src/Hogtools/gradientMex.cpp:286:55: warning: unused variable ‘nb’ [-Wunused-variable]
   float *N, *R; const int hb=h/binSize, wb=w/binSize, nb=hb*wb;
                                                       ^
[ 28%] Linking CXX static library libfeatures.a
[ 28%] Built target features
[ 42%] Building CXX object src/CMakeFiles/kcf.dir/kcf.cpp.o
In file included from /home/sojoyoo/pedestrian_gaffey/src/kcf.h:6:0,
                 from /home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:1:
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:50: error: ‘function’ in namespace ‘std’ does not name a template type
     ComplexMat_<T> mat_const_operator(const std::function<void(std::complex<T> 
                                                  ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:58: error: expected ‘,’ or ‘...’ before ‘<’ token
     ComplexMat_<T> mat_const_operator(const std::function<void(std::complex<T> 
                                                          ^
In file included from /home/sojoyoo/pedestrian_gaffey/src/kcf.h:7:0,
                 from /home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:1:
/home/sojoyoo/pedestrian_gaffey/src/extractfeatures.h:12:56: warning: unused parameter ‘useCNNFeature’ [-Wunused-parameter]
  Features(bool useHOGFeature, bool useYUVFeature, bool useCNNFeature):useHOGFea
                                                        ^
In file included from /home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:1:0:
/home/sojoyoo/pedestrian_gaffey/src/kcf.h: In constructor ‘KCF::KCF(double, double, double, int*)’:
/home/sojoyoo/pedestrian_gaffey/src/kcf.h:36:29: warning: ‘KCF::outputSigmaFactor’ will be initialized after [-Wreorder]
  double outputSigmaFactor = 0.1;
                             ^
/home/sojoyoo/pedestrian_gaffey/src/kcf.h:33:18: warning:   ‘double KCF::lambda’ [-Wreorder]
  double lambda = 1e-4;
                  ^
/home/sojoyoo/pedestrian_gaffey/src/kcf.h:18:2: warning:   when initialized here [-Wreorder]
  KCF(double gaussSigma, double outputSigmaFactor, double lambda, int *win):
  ^
In file included from /home/sojoyoo/pedestrian_gaffey/src/kcf.h:6:0,
                 from /home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:1:
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp: In instantiation of ‘ComplexMat_<T> ComplexMat_<T>::operator+(const T&) const [with T = float]’:
/home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:53:35:   required from here
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:93:34: error: no matching function for call to ‘ComplexMat_<float>::mat_const_operator(ComplexMat_<T>::operator+(const T&) const [with T = float]::<lambda(std::complex<float>&)>) const’
         return mat_const_operator( [&rhs](std::complex<T> & c) { c += rhs; });
                                  ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:20: note: candidate: ComplexMat_<T> ComplexMat_<T>::mat_const_operator(int) const [with T = float]
     ComplexMat_<T> mat_const_operator(const std::function<void(std::complex<T> 
                    ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:20: note:   no known conversion for argument 1 from ‘ComplexMat_<T>::operator+(const T&) const [with T = float]::<lambda(std::complex<float>&)>’ to ‘int’
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp: In instantiation of ‘ComplexMat_<T> ComplexMat_<T>::operator*(const T&) const [with T = float]’:
/home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:106:36:   required from here
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:89:34: error: no matching function for call to ‘ComplexMat_<float>::mat_const_operator(ComplexMat_<T>::operator*(const T&) const [with T = float]::<lambda(std::complex<float>&)>) const’
         return mat_const_operator( [&rhs](std::complex<T> & c) { c *= rhs; });
                                  ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:20: note: candidate: ComplexMat_<T> ComplexMat_<T>::mat_const_operator(int) const [with T = float]
     ComplexMat_<T> mat_const_operator(const std::function<void(std::complex<T> 
                    ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:20: note:   no known conversion for argument 1 from ‘ComplexMat_<T>::operator*(const T&) const [with T = float]::<lambda(std::complex<float>&)>’ to ‘int’
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp: In instantiation of ‘ComplexMat_<T> ComplexMat_<T>::sqr_mag() const [with T = float]’:
/home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:302:51:   required from here
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:46:34: error: invalid user-defined conversion from ‘ComplexMat_<T>::sqr_mag() const [with T = float]::<lambda(std::complex<float>&)>’ to ‘int’ [-fpermissive]
         return mat_const_operator( [](std::complex<T> & c) { c = c.real()*c.rea
                                  ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:46:58: note: candidate is: ComplexMat_<T>::sqr_mag() const [with T = float]::<lambda(std::complex<float>&)>::operator void (*)(std::complex<float>&)() const <near match>
         return mat_const_operator( [](std::complex<T> & c) { c = c.real()*c.rea
                                                          ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:46:58: note:   no known conversion from ‘void (*)(std::complex<float>&)’ to ‘int’
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:20: note:   initializing argument 1 of ‘ComplexMat_<T> ComplexMat_<T>::mat_const_operator(int) const [with T = float]’
     ComplexMat_<T> mat_const_operator(const std::function<void(std::complex<T> 
                    ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp: In instantiation of ‘ComplexMat_<T> ComplexMat_<T>::conj() const [with T = float]’:
/home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:302:68:   required from here
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:51:34: error: invalid user-defined conversion from ‘ComplexMat_<T>::conj() const [with T = float]::<lambda(std::complex<float>&)>’ to ‘int’ [-fpermissive]
         return mat_const_operator( [](std::complex<T> & c) { c = std::complex<T
                                  ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:51:58: note: candidate is: ComplexMat_<T>::conj() const [with T = float]::<lambda(std::complex<float>&)>::operator void (*)(std::complex<float>&)() const <near match>
         return mat_const_operator( [](std::complex<T> & c) { c = std::complex<T
                                                          ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:51:58: note:   no known conversion from ‘void (*)(std::complex<float>&)’ to ‘int’
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:141:20: note:   initializing argument 1 of ‘ComplexMat_<T> ComplexMat_<T>::mat_const_operator(int) const [with T = float]’
     ComplexMat_<T> mat_const_operator(const std::function<void(std::complex<T> 
                    ^
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp: In instantiation of ‘ComplexMat_<T> ComplexMat_<T>::mat_const_operator(int) const [with T = float]’:
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:93:34:   required from ‘ComplexMat_<T> ComplexMat_<T>::operator+(const T&) const [with T = float]’
/home/sojoyoo/pedestrian_gaffey/src/kcf.cpp:53:35:   required from here
/home/sojoyoo/pedestrian_gaffey/src/complexmat.hpp:148:19: error: ‘op’ was not declared in this scope
                 op(*lhs);
                   ^
src/CMakeFiles/kcf.dir/build.make:62: recipe for target 'src/CMakeFiles/kcf.dir/kcf.cpp.o' failed
make[2]: *** [src/CMakeFiles/kcf.dir/kcf.cpp.o] Error 1
CMakeFiles/Makefile2:125: recipe for target 'src/CMakeFiles/kcf.dir/all' failed
make[1]: *** [src/CMakeFiles/kcf.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Do you have any idea to handle this ?thank you !

**Comment by Gaffey** [comment]
I'm sorry that this repository is not finished. You can just use the code I referred in the README.

**Comment by albertyou2** [comment]
hi @Gaffey 
Will this repo be finished in the future?if it will be ,i am very happy to wait!
thanks

**Comment by Gaffey** [comment]
Not in the near future
